class RoundE{
	constructor (cp){
		this.roundMap;
	}
	init(){
		this.setData();
	}

  getData(serNbr){console.log("Round. getData  = " + serNbr);
	  return this.roundMap.get(serNbr);
  }
  setData(){
	this.roundMap = new Map();
	    this.roundMap.set(',AA.Een0000',',AA.Een00001,EdUGames tm,,9,,,,Te,,,aPRA1_40 zPRA1_15 ,,,,,Test/GameE,Pick the item that is not similar to the other items in the row.,,Rows=4 Cols=3 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 SingleScreen=Yes Sort=Yes,One;Red;Blue,San Diego;California;Oregon,Tree;Car;Bus,Yellow;One;Two,Radio;Chair;Bed,George Washington;Superman;Spiderman');
    this.roundMap.set('AA.Een00002',',AA.Een00002,EdUGames tm,20020501,9,,,,Te,,,aPRA1_40 zPRA1_15,,,,,Test/GameE,Select the single letter  [No Sort] Multi-Screen No Zones,,Rows=4 Cols=3 FntSize=35 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=No Sort=No ,A;AA;AAA;,B;BB;BBB;,C;CC;CCC;,D;DD;DDD;,E;EE;EEE;,F;FF;FFF;,G;GG;GGG;,H;HH;HHH;,I;II;III;,J;JJ;JJJ;,K;KK;KKK;,L;LL;LLL;,M;MM;MMM;,N;NN;NNN;,O;OO;OOO;,P;PP;PPP;,Q;QQ;QQQ;,R;RR;RRR;,S;SS;SSS;,T;TT;TTT;,U;UU;UUU;,V;VV;VVV;,W;WW;WWW;,X;XX;XXX;,Y;YY;YYY;,Z;ZZ;ZZZ;');
    this.roundMap.set('AA.Een00003',',AA.Een00003,EdUGames tm,20020501,9,,,,Te,,,aPRA1_40 zPRA1_15,,,,,Test/GameE,Select the single letter  [Sort] Multi-Screen 3 Zones,,Rows=4 Cols=3 FntSize=35 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=No Sort=Yes Zones=Yes,1A;AA;AAA;,1B;BB;BBB;,1C;CC;CCC;,1D;DD;DDD;,1E;EE;EEE;,1F;FF;FFF;,1G;GG;GGG;,1H;HH;HHH;,1I;II;III;,1J;JJ;JJJ;,1K;KK;KKK;,1L;LL;LLL;,1M;MM;MMM;,1N;NN;NNN;,1O;OO;OOO;,1P;PP;PPP;,1Q;QQ;QQQ;,1R;RR;RRR;,1S;SS;SSS;,1T;TT;TTT;,1U;UU;UUU;,1V;VV;VVV;,1W;WW;WWW;,1X;XX;XXX;,1Y;YY;YYY;,1Z;ZZ;ZZZ;');
    this.roundMap.set('AA.Een00004',',AA.Een00004,EdUGames tm,20020501,9,,,,Te,,,aPRA1_40 zPRA1_15,,,,,Test/GameE,Select the single letter  [Sort] Multi-Screen No Zones,,Rows=4 Cols=3 FntSize=35 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=No Sort=Yes ,A;AA;AAA;,B;BB;BBB;,C;CC;CCC;,D;DD;DDD;,E;EE;EEE;,F;FF;FFF;,G;GG;GGG;,H;HH;HHH;,I;II;III;,J;JJ;JJJ;,K;KK;KKK;,L;LL;LLL;,M;MM;MMM;,N;NN;NNN;,O;OO;OOO;,P;PP;PPP;,Q;QQ;QQQ;,R;RR;RRR;,S;SS;SSS;,T;TT;TTT;,U;UU;UUU;,V;VV;VVV;,W;WW;WWW;,X;XX;XXX;,Y;YY;YYY;,Z;ZZ;ZZZ;');
    this.roundMap.set('AA.Een00005',',AA.Een00005,EdUGames tm,20020501,9,,,,Te,,,aPRA1_40 zPRA1_15,,,,,Test/GameE,Select the single letter  [No Sort] Multi-Screen 3 Zones,,Rows=4 Cols=3 FntSize=35 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=No Sort=No Zones=Yes,0A;AA;AAA;,0B;BB;BBB;,0C;CC;CCC;,0D;DD;DDD;,0E;EE;EEE;,0F;FF;FFF;,0G;GG;GGG;,0H;HH;HHH;,0I;II;III;,1J;JJ;JJJ;,1K;KK;KKK;,1L;LL;LLL;,1M;MM;MMM;,1N;NN;NNN;,1O;OO;OOO;,1P;PP;PPP;,1Q;QQ;QQQ;,0R;RR;RRR;,1S;SS;SSS;,1T;TT;TTT;,2U;UU;UUU;,2V;VV;VVV;,2W;WW;WWW;,2X;XX;XXX;,2Y;YY;YYY;,2Z;ZZ;ZZZ;');
    this.roundMap.set('AA.Een00006',',AA.Een00006,EdUGames tm,20020501,9,,,,Te,,,aPRA1_40 zPRA1_15,,,,,Test/GameE,Select the single letter  [No Sort] 10 Rows Single-Screen No Zones,,Rows=10 Cols=3 FntSize=35 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=Yes Sort=No ,A;AA;AAA;,B;BB;BBB;,C;CC;CCC;,D;DD;DDD;,E;EE;EEE;,F;FF;FFF;,G;GG;GGG;,H;HH;HHH;,I;II;III;,J;JJ;JJJ;,K;KK;KKK;,L;LL;LLL;,M;MM;MMM;,N;NN;NNN;,O;OO;OOO;,P;PP;PPP;,Q;QQ;QQQ;,R;RR;RRR;,S;SS;SSS;,T;TT;TTT;,U;UU;UUU;,V;VV;VVV;,W;WW;WWW;,X;XX;XXX;,Y;YY;YYY;,Z;ZZ;ZZZ;');
    this.roundMap.set('AA.Een00007',',AA.Een00007,EdUGames tm,20020501,9,,,,Te,,,aPRA1_40 zPRA1_15,,,,,Test/GameE,Select the single letter  [Sort] Single-Screen 3 Zones,,Rows=4 Cols=3 FntSize=35 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=Yes Sort=Yes Zones=Yes,1A;AA;AAA;,1B;BB;BBB;,1C;CC;CCC;,1D;DD;DDD;,1E;EE;EEE;,1F;FF;FFF;,1G;GG;GGG;,1H;HH;HHH;,1I;II;III;,1J;JJ;JJJ;,1K;KK;KKK;,1L;LL;LLL;,1M;MM;MMM;,1N;NN;NNN;,1O;OO;OOO;,1P;PP;PPP;,1Q;QQ;QQQ;,1R;RR;RRR;,1S;SS;SSS;,1T;TT;TTT;,1U;UU;UUU;,1V;VV;VVV;,1W;WW;WWW;,1X;XX;XXX;,1Y;YY;YYY;,1Z;ZZ;ZZZ;');
    this.roundMap.set('AA.Een00008',',AA.Een00008,EdUGames tm,20020501,9,,,,Te,,,aPRA1_40 zPRA1_15,,,,,Test/GameE,Select the single letter  [Sort] Single-Screen No Zones,,Rows=4 Cols=3 FntSize=35 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=Yes Sort=Yes ,A;AA;AAA;,B;BB;BBB;,C;CC;CCC;,D;DD;DDD;,E;EE;EEE;,F;FF;FFF;,G;GG;GGG;,H;HH;HHH;,I;II;III;,J;JJ;JJJ;,K;KK;KKK;,L;LL;LLL;,M;MM;MMM;,N;NN;NNN;,O;OO;OOO;,P;PP;PPP;,Q;QQ;QQQ;,R;RR;RRR;,S;SS;SSS;,T;TT;TTT;,U;UU;UUU;,V;VV;VVV;,W;WW;WWW;,X;XX;XXX;,Y;YY;YYY;,Z;ZZ;ZZZ;');
    this.roundMap.set('AA.Een00009',',AA.Een00009,EdUGames tm,20020501,9,,,,Te,,,aPRA1_40 zPRA1_15,,,,,Test/GameE,Select the single letter  [No Sort] Single-Screen 3 Zones,,Rows=4 Cols=3 FntSize=35 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=Yes Sort=No Zones=Yes,0A;AA;AAA;,0B;BB;BBB;,0C;CC;CCC;,0D;DD;DDD;,0E;EE;EEE;,0F;FF;FFF;,0G;GG;GGG;,0H;HH;HHH;,0I;II;III;,1J;JJ;JJJ;,1K;KK;KKK;,1L;LL;LLL;,1M;MM;MMM;,1N;NN;NNN;,1O;OO;OOO;,1P;PP;PPP;,1Q;QQ;QQQ;,0R;RR;RRR;,1S;SS;SSS;,1T;TT;TTT;,2U;UU;UUU;,2V;VV;VVV;,2W;WW;WWW;,2X;XX;XXX;,2Y;YY;YYY;,2Z;ZZ;ZZZ;');
    this.roundMap.set('AA.Een00010',',AA.Een00010,EdUGames tm,20021015,10,ThStHi LoPoCo,HiWo GeWo,,,country;historic items,,aPRA1_50 zPRA1_15,,,,,Countries/Historic Things,Pick the one item in each row that is not in the same Country as the others in the row,^AA.DCL.C.332374,Rows=4 Cols=3 FntSize=16 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=No Sort=No ,Taj Mahal:^AA.DCL.A.185153;The Globe Theater:^AA.DCL.A.120022;Saint Paul~s Cathedral:^AA.DCL.A.182063;Big Ben:^AA.DCL.A.160023,The Acropolis:^AA.DCL.A.156043;The Holy See:^AA.DCL.A.092133;The Colosseum:^AA.DCL.A.163153;Sistine Chapel:^AA.DCL.A.183023,Great Wall of China:^AA.DCL.A.168103;Maginot Line:^AA.DCL.A.218013;Eiffel Tower:^AA.DCL.A.166013;Cathedral of Chartres:^AA.DCL.A.163043,Sphinx:^AA.DCL.A.183112;The Pentagon:^AA.DCL.A.323052;The Watergate:^AA.DCL.A.284093;Transcontinental Railroad:^AA.DCL.A.283012');
    this.roundMap.set('AA.Een00011',',AA.Een00011,EdUGames tm,20041106,4,,,,,,,aPRA1_50 zPRA1_15,,,,,Items/Category,Pick the one item is each horizontal row that is different from the others in the row.,,Rows=5 Cols=4 FntSize=18 FntColor=blue BkGndColor=yellow LnCnt=1 SingleScreen=No Sort=No ,Book;Car;Bike;Boat,Mary;Joe;Mike;Peter,House;Apple;Orange;Bannana,Stove;Tree;Bush;Vine,Radio;Football;Tennis;Golf;');
    this.roundMap.set('AA.Een00012',',AA.Een00012,EdUGames tm,,9,,,,Te,,,aPRA1_40 zPRA1_15 ,,,,,Test/TestTest ,Pick the item that is not similar to the other items in the row.,,Rows=4 Cols=3 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 SingleScreen=Yes Sort=Yes,One;Red;Blue,San Diego;California;Oregon,Tree;Car;Bus,Yellow;One;Two,Radio;Chair;Bed,George Washington;Superman;Spiderman');
    this.roundMap.set('AA.Een00013',',AA.Een00013,EdUGames tm,,9,,,,Te,,,aPRA1_40 zPRA1_15 ,,,,,Test/GameE,Pick the item that is not similar to the other items in the row.,,Rows=4 Cols=3 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 SingleScreen=Yes Sort=Yes,One;Red;Blue,San Diego;California;Oregon,Tree;Car;Bus,Yellow;One;Two,Radio;Chair;Bed,George Washington;Superman;Spiderman');
    this.roundMap.set('AA.Een00014',',AA.Een00014,EdUGames tm,,9,,,,Te,,,aPRA1_40 zPRA1_15 ,,,,,Test/GameE,Pick the item that is not similar to the other items in the row.,,Rows=4 Cols=3 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 SingleScreen=Yes Sort=Yes,One;Red;Blue,San Diego;California;Oregon,Tree;Car;Bus,Yellow;One;Two,Radio;Chair;Bed,George Washington;Superman;Spiderman');
    this.roundMap.set('AA.Een00015',',AA.Een00015,EdUGames tm,,9,,,,Te,,,aPRA1_40 zPRA1_15 ,,,,,Test/GameE,Pick the item that is not similar to the other items in the row.,,Rows=4 Cols=3 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 SingleScreen=Yes Sort=Yes,One;Red;Blue,San Diego;California;Oregon,Tree;Car;Bus,Yellow;One;Two,Radio;Chair;Bed,George Washington;Superman;Spiderman');
    this.roundMap.set('AA.Een00016',',AA.Een00016,Ed-U-Games tm,20180226,9,,,,,,,aPRA1_50 zPRA1_30,,,,,Test,Wich is different.,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00017',',AA.Een00017,Ed-U-Games tm,20180226,9,,,,,,,aPRA1_50 zPRA1_30,,,,,Test,Wich is different.,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00018',',AA.Een00018,Ed-U-Games tm,20180226,9,,,,,,,aPRA1_50 zPRA1_30,,,,,Test,Wich is different.,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00019',',AA.Een00019,Ed-U-Games tm,20180228,9,,,,,,,aPRA1_50 zPRA1_30,,,,,test,Test,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00020',',AA.Een00020,Ed-U-Games tm,20180228,9,,,,,,,aPRA1_50 zPRA1_30,,,,,test,Test,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00021',',AA.Een00021,Ed-U-Games tm,20180228,9,,,,,,,aPRA1_50 zPRA1_30,,,,,test,Test,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00022',',AA.Een00022,Ed-U-Games tm,20180228,9,,,,,,,aPRA1_50 zPRA1_30,,,,,test,Test,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00023',',AA.Een00023,Ed-U-Games tm,20180228,9,,,,,,,aPRA1_50 zPRA1_30,,,,,test,Test,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00024',',AA.Een00024,Ed-U-Games tm,20180228,9,,,,,,,aPRA1_50 zPRA1_30,,,,,test,Test,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');
    this.roundMap.set('AA.Een00001',',AA.Een00025,Ed-U-Games tm,20180228,9,,,,,,,aPRA1_50 zPRA1_30,,,,,test,Test,,Rows=5 Cols=5 FntSize=12 FntColor=black BkGndColor=white LnCnt=1 FlushNbr=1 SingleScreen=No Sort=Yes,Dog;Red;Blue;Green;Yellow,Car;Apple;Bannana;Orange;Pear,House;Apple;Bannana;Orange;Pear,TiVo;Apple;Bannana;Orange;Pear,Radio;Apple;Bannana;Orange;Pear');






  }

}// JavaScript source code
